package com.tss.loanEmiSchedular.enums;

public enum AuditAction {

    LOAN_CREATED,
    LOAN_APPLIED,
    LOAN_APPROVED,
    LOAN_REJECTED,
    LOAN_STATUS_CHANGED,
    LOAN_CANCELLED,
    LOAN_CLOSED,

    EMI_GENERATED,
    EMI_PAID,
    EMI_PAYMENT_DONE,
    EMI_PAYMENT_FAILED,
    EMI_MODIFIED,
    LOAN_STRATEGY_CHANGED,

    PAYMENT_REMINDER_SENT,
    EMI_MARKED_OVERDUE
}
